---

- hosts: localhost
  connection: local
  gather_facts: false
  become: true
  
  vars:
    key_name: eng130
    region: eu-west-1
    image: ami-00f499a80f4608e1b # image of ubunutu 18.04
    id: "eng130 ansible app"
    sec_group: "sg-0eb5c3aadbe39e72d"
  
  tasks:

    - name: Facts
      block:

      - name: Get instances facts
        ec2_instance_facts:
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"
          region: "{{ region }}"
        register: result
   
    #  - name: Instances ID
     #   debug:
      #    msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
       # loop: "{{ result.instances }}"

      tags: always

    - name: provisioning EC2 instances
      block:

      - name: Upload public key to AWS
        ec2_key:
          name: "{{ key_name }}"
          key_material: "{{ lookup('file', '~/.ssh/{{ key_name }}.pub') }}"
          region: "{{ region }}"
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"

      - name: Provision instance(s)
        ec2:
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"
          key_name: "{{ key_name }}"
          id: "{{ id }}"
          group_id: "{{ sec_group }}"
          image: "{{ image }}"
          instance_type: t2.micro
          region: "{{ region }}"
          wait: true
         # count: 1
         #  exact_count: 2
         # count_tag:
         #    Name: App
          instance_tags:
             Name: subhaans-ansible-app
        tags: ['never', 'create_ec2']