---
# host is our db

- hosts: db

# Gather all the data
  gather_facts: yes

# allow admin access
  become: true

# Carry out the tasks
  tasks:
  - name: install mongodb
    apt: pkg=mongodb state=present
  

  - name: Remove mongodb file (delete file)
    file:
      path: /etc/mongodb.conf
      state: absent

    
  - name: Touch mongodb.conf file
    file:
      path: /etc/mongodb.conf
      state: touch
      mode: u=rw,g=r,o=r
      
  - name: Populate Conf file
    blockinfile:
      path: /etc/mongodb.conf
      block: |
        storage:
          dbPath: /var/lib/mongodb
          journal:
            enabled: true
        systemLog:
          destination: file
          logAppend: true
          path: /var/log/mongodb/mongod.log
        net:
          port: 27017
          bindIp: 0.0.0.0
          
  - name: Restart mongodb
    become: true
    shell: systemctl restart mongodb
    
  - name: enable mongodb
    become: true
    shell: systemctl enable mongodb
    
  - name: start mongodb
    become: true
    shell: systemctl start mongodb